apiVersion: apps/v1
kind: Deployment
metadata:
  name: bio-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bio-web
  template:
    metadata:
      labels:
        app: bio-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000