apiVersion: apps/v1
kind: Deployment
metadata:
  name: dit-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dit-web
  template:
    metadata:
      labels:
        app: dit-web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80